services:
  - type: web
    name: webbuilder-api
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: webbuilder-super-secret-jwt-key-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EXPORT_CREDIT_COST
        value: 200
      - key: INITIAL_USER_CREDITS
        value: 500
      - key: DATABASE_URL
        fromDatabase:
          name: webbuilder-db
          property: connectionString

databases:
  - name: webbuilder-db
    plan: free
    region: frankfurt
